#!/bin/bash

# Generate unit tests based on git diff
# This script analyzes changed files and generates corresponding unit tests

set -euo pipefail

# Configuration
SKIP_TEST_GENERATION="${SKIP_TEST_GENERATION:-false}"
PREVIEW_MODE="${PREVIEW_MODE:-false}"
ANALYZE_DIFF="${ANALYZE_DIFF:-true}"
OUTPUT_DIR="${OUTPUT_DIR:-tests/generated}"
LOG_LEVEL="${LOG_LEVEL:-INFO}"
COVERAGE_THRESHOLD="${COVERAGE_THRESHOLD:-80}"
TEST_LANGUAGE="${TEST_LANGUAGE:-}"

# Skip if disabled
if [[ "${SKIP_TEST_GENERATION}" == "true" ]]; then
  exit 0
fi

# Create logs directory
mkdir -p logs/copilot

# Logging function
log() {
  local level="$1"
  shift
  local message="$*"
  local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  
  if [[ "${LOG_LEVEL}" != "ERROR" ]] || [[ "${level}" == "ERROR" ]]; then
    echo "[${timestamp}] [${level}] ${message}" >> logs/copilot/generation.log
  fi
}

# Detect language from file extension
detect_language() {
  local file="$1"
  case "${file}" in
    *.py) echo "python" ;;
    *.js|*.ts|*.jsx|*.tsx) echo "javascript" ;;
    *.cc|*.cpp|*.cxx|*.h|*.hpp) echo "cpp" ;;
    *) echo "unknown" ;;
  esac
}

# Get changed files
get_changed_files() {
  local files
  
  # Get both staged and unstaged changes
  files=$(git diff --name-only --cached)
  files+=$(printf '\n'; git diff --name-only)
  
  # Remove duplicates and filter out deleted files
  echo "${files}" | sort -u | while read -r file; do
    if [[ -f "${file}" ]]; then
      echo "${file}"
    fi
  done
}

# Generate test file name based on source file
get_test_filename() {
  local source_file="$1"
  local language="$2"
  local filename=$(basename "${source_file}")
  local name="${filename%.*}"
  
  case "${language}" in
    python)
      echo "${OUTPUT_DIR}/test_${name}.py"
      ;;
    javascript)
      echo "${OUTPUT_DIR}/${name}.test.js"
      ;;
    cpp)
      echo "${OUTPUT_DIR}/${name}_test.cc"
      ;;
    *)
      echo ""
      ;;
  esac
}

# Generate test template based on language
generate_test_template() {
  local source_file="$1"
  local language="$2"
  local test_file="$3"
  
  case "${language}" in
    python)
      cat > "${test_file}" << 'EOF'
"""
Auto-generated unit tests for module changes.
Generated by: generate-test hook
Date: $(date)

IMPORTANT: This is a template. Please review and enhance with:
- Edge cases
- Error handling
- Integration scenarios
- Performance tests
"""

import pytest
from unittest.mock import Mock, patch

# TODO: Update import path based on actual module
# from your_module import YourClass


class TestChanges:
    """Tests for recently changed functionality."""

    @pytest.fixture
    def setup(self):
        """Setup test fixtures."""
        # TODO: Initialize test fixtures
        pass

    def test_basic_functionality(self, setup):
        """Test basic functionality of changed code."""
        # TODO: Implement test
        assert True

    def test_error_handling(self, setup):
        """Test error handling in changed code."""
        # TODO: Implement error handling test
        assert True

    def test_edge_cases(self, setup):
        """Test edge cases."""
        # TODO: Implement edge case tests
        assert True
EOF
      ;;
    javascript)
      cat > "${test_file}" << 'EOF'
/**
 * Auto-generated unit tests for module changes.
 * Generated by: generate-test hook
 * Date: $(date)
 *
 * IMPORTANT: This is a template. Please review and enhance with:
 * - Edge cases
 * - Error handling
 * - Mock implementations
 * - Integration tests
 */

describe('ChangedModule', () => {
  beforeEach(() => {
    // Setup mocks and fixtures
  });

  it('should handle basic functionality', () => {
    // TODO: Implement test
    expect(true).toBe(true);
  });

  it('should handle errors gracefully', () => {
    // TODO: Implement error handling test
    expect(true).toBe(true);
  });

  it('should handle edge cases', () => {
    // TODO: Implement edge case tests
    expect(true).toBe(true);
  });
});
EOF
      ;;
    cpp)
      cat > "${test_file}" << 'EOF'
#include <gtest/gtest.h>
// TODO: Include your headers
// #include "your_module.h"

// Auto-generated unit tests for module changes.
// Generated by: generate-test hook
//
// IMPORTANT: This is a template. Please review and enhance with:
// - Edge cases
// - Error handling
// - Mock objects
// - Integration tests

class ChangedModuleTest : public ::testing::Test {
protected:
    void SetUp() override {
        // TODO: Setup test fixtures
    }

    void TearDown() override {
        // TODO: Cleanup
    }
};

TEST_F(ChangedModuleTest, BasicFunctionality) {
    // TODO: Implement test
    EXPECT_TRUE(true);
}

TEST_F(ChangedModuleTest, ErrorHandling) {
    // TODO: Implement error handling test
    EXPECT_TRUE(true);
}

TEST_F(ChangedModuleTest, EdgeCases) {
    // TODO: Implement edge case tests
    EXPECT_TRUE(true);
}
EOF
      ;;
  esac
}

# Main execution
main() {
  log "INFO" "=== Test Generation Hook Started ==="
  
  # Create output directory
  mkdir -p "${OUTPUT_DIR}"
  
  # Get changed files
  changed_files=$(get_changed_files)
  
  if [[ -z "${changed_files}" ]]; then
    log "INFO" "No changed files detected"
    echo "✓ No changes to analyze"
    exit 0
  fi
  
  # Count statistics
  local total_files=0
  local generated_tests=0
  local skipped_files=0
  
  # Process each changed file
  while IFS= read -r changed_file; do
    ((total_files++))
    
    # Skip certain directories/patterns
    if [[ "${changed_file}" =~ tests/|spec/|.*\.test\.|.*_test\. ]]; then
      log "INFO" "Skipping test file: ${changed_file}"
      ((skipped_files++))
      continue
    fi
    
    # Detect language
    local language=$(detect_language "${changed_file}")
    
    if [[ "${language}" == "unknown" ]]; then
      log "INFO" "Skipping unsupported file type: ${changed_file}"
      ((skipped_files++))
      continue
    fi
    
    # Generate test filename
    local test_file=$(get_test_filename "${changed_file}" "${language}")
    
    if [[ -z "${test_file}" ]]; then
      log "ERROR" "Could not generate test filename for: ${changed_file}"
      ((skipped_files++))
      continue
    fi
    
    # Generate test template
    if [[ "${PREVIEW_MODE}" == "true" ]]; then
      log "INFO" "PREVIEW: Would generate test for ${changed_file} -> ${test_file}"
      echo "  → Would create: ${test_file}"
    else
      generate_test_template "${changed_file}" "${language}" "${test_file}"
      log "INFO" "Generated test file: ${test_file}"
      echo "  ✓ Generated: ${test_file}"
      ((generated_tests++))
    fi
  done <<< "${changed_files}"
  
  # Summary
  log "INFO" "=== Test Generation Complete ==="
  log "INFO" "Total files analyzed: ${total_files}, Generated: ${generated_tests}, Skipped: ${skipped_files}"
  
  echo ""
  echo "📊 Summary:"
  echo "   Files analyzed: ${total_files}"
  echo "   Tests generated: ${generated_tests}"
  echo "   Files skipped: ${skipped_files}"
  
  if [[ "${PREVIEW_MODE}" == "true" ]]; then
    echo ""
    echo "⚠️  PREVIEW MODE - No files were actually created"
  else
    echo ""
    echo "✅ Test generation complete. Review and enhance generated tests:"
    echo "   ${OUTPUT_DIR}/"
  fi
  
  exit 0
}

main "$@"
